#!/bin/bash

export MY_HOST_IP="$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1)"

echo "-------------------------------------------------"
echo "MY_HOST_IP = $MY_HOST_IP"
echo "-------------------------------------------------"
