node('generic'){
    stage('checkout'){
        checkout scm
    }
    dir('demo/apps/java-calc'){
        stage('maven-build'){
            sh './mvnw -B clean install'
        }
        stage('archive-tests'){
            junit 'target/surefire-reports/TEST-*.xml'
        }
    }
}