node('cloudbees-tools'){
    stage('checkout'){
        checkout scm
    }
    dir('demo/apps/nodejs-calc'){
        stage('install-deps'){
            sh 'npm install'
        }
        stage('test'){
            sh 'npm test'
        }
        stage('archive-tests'){
            junit 'test-results.xml'
        }
    }
}