pipelineJob('sample-job-created-by-seed'){
    definition{
        cpsScm{
            scm{
                git{
                    branch('kubernetes-example')
                    remote{
                        url('https://github.com/odavid/my-bloody-jenkins.git')
                    }
                    extensions{
                        cleanBeforeCheckout()
                    }
                }
            }
            scriptPath('examples/jobs/sample-job/Jenkinsfile')
        }
    }
}