#!/bin/bash
set -e

echo "DOCKER_REPO=$DOCKER_REPO"
echo "SOURCE_BRANCH=$SOURCE_BRANCH"
echo "SOURCE_COMMIT=$SOURCE_COMMIT"
echo "COMMIT_MSG=$COMMIT_MSG"
echo "DOCKER_REPO=$DOCKER_REPO"
echo "DOCKERFILE_PATH=$DOCKERFILE_PATH"
echo "CACHE_TAG=$CACHE_TAG"
echo "IMAGE_NAME=$IMAGE_NAME"

docker build --build-arg FROM_TAG=2.150.3-alpine -f $DOCKERFILE_PATH -t $IMAGE_NAME-alpine .
docker tag $IMAGE_NAME-alpine $IMAGE_NAME

docker build --build-arg FROM_TAG=2.150.3-slim -f $DOCKERFILE_PATH -t $IMAGE_NAME-slim .
docker build --build-arg FROM_TAG=2.150.3 -f $DOCKERFILE_PATH -t $IMAGE_NAME-debian .