#!/bin/bash
set -e

# Skip if latest
[[ "$CACHE_TAG" == 'latest' ]] && exit 0

NEW_TAG=$(echo $CACHE_TAG | cut -d '-' -f 1)

docker tag $IMAGE_NAME $DOCKER_REPO:$NEW_TAG
docker tag $IMAGE_NAME $DOCKER_REPO:lts

docker push $DOCKER_REPO:$NEW_TAG
docker push $DOCKER_REPO:lts
