#!/bin/bash
set -e

# Skip if latest
[[ "$SOURCE_BRANCH" == 'master' ]] && exit 0

echo "DOCKER_REPO=$DOCKER_REPO"
echo "SOURCE_BRANCH=$SOURCE_BRANCH"
echo "SOURCE_COMMIT=$SOURCE_COMMIT"
echo "COMMIT_MSG=$COMMIT_MSG"

TAG=$(echo $SOURCE_BRANCH | sed 's/v//g')
NEW_TAG=$(echo $TAG | cut -d '-' -f 1)

echo "TAG=$TAG"
echo "NEW_TAG=$NEW_TAG"

docker tag "$DOCKER_REPO:$TAG" "$DOCKER_REPO:$NEW_TAG"
docker tag "$DOCKER_REPO:$TAG" "$DOCKER_REPO:lts"

docker push "$DOCKER_REPO:$NEW_TAG"
docker push "$DOCKER_REPO:lts"
